import type { Scenario } from '@vajra/contracts';

/**
 * Scenario presets. Numbers follow climatology:
 * - Nor'westers (Kalbaisakhi): Apr-May, 14-19 IST, move from NW to SE at 40-70 km/h, CAPE 2500-4000 J/kg.
 * - Bihar/Jharkhand: highest CG lightning deaths in India, farmers in fields in the afternoon.
 * - Mumbai monsoon: high PW (>60 mm), weak shear, slow cells, heavy rain dominant.
 * - Delhi dust-thunder: May-Jun, dry sub-cloud layer, strong gusts (downbursts), moderate lightning.
 */
export const SCENARIOS: Scenario[] = [
  {
    id: 'kolkata-kalbaisakhi',
    name: 'Kolkata Kalbaisakhi squall line',
    region: 'Gangetic West Bengal',
    regime: 'premonsoon_norwester',
    center: [87.9, 22.9],
    zoom: 7.1,
    bbox: [85.4, 21.0, 90.4, 24.8],
    steeringDeg: 125,
    steeringKmh: 52,
    startHourIST: 15.5,
    month: 4,
    cape: 3400,
    shear: 19,
    pw: 48,
    cells: [
      { lng: 86.3, lat: 23.9, type: 'squall', strength: 0.95, delayMin: 0 },
      { lng: 86.9, lat: 24.2, type: 'multicell', strength: 0.75, delayMin: 8 },
      { lng: 87.6, lat: 22.2, type: 'pulse', strength: 0.45, delayMin: 20 },
      { lng: 88.9, lat: 23.6, type: 'pulse', strength: 0.4, delayMin: 35 },
    ],
    spawnRatePerHour: 5,
    landUse: 'mixed',
    description: 'A pre-monsoon squall line forms over the Chota Nagpur plateau and races SE toward Kolkata at 50+ km/h. Gusts can exceed 80 km/h.',
  },
  {
    id: 'bihar-jharkhand-outbreak',
    name: 'Bihar-Jharkhand lightning outbreak',
    region: 'Bihar / Jharkhand',
    regime: 'premonsoon_norwester',
    center: [85.6, 24.9],
    zoom: 7.0,
    bbox: [83.2, 23.0, 88.0, 27.0],
    steeringDeg: 100,
    steeringKmh: 30,
    startHourIST: 13.5,
    month: 6,
    cape: 3000,
    shear: 12,
    pw: 55,
    cells: [
      { lng: 84.6, lat: 25.3, type: 'multicell', strength: 0.85, delayMin: 0 },
      { lng: 85.1, lat: 25.9, type: 'pulse', strength: 0.6, delayMin: 5 },
      { lng: 85.8, lat: 24.3, type: 'multicell', strength: 0.7, delayMin: 12 },
      { lng: 84.2, lat: 24.6, type: 'pulse', strength: 0.55, delayMin: 25 },
      { lng: 86.5, lat: 25.1, type: 'pulse', strength: 0.5, delayMin: 40 },
    ],
    spawnRatePerHour: 8,
    landUse: 'farmland',
    description: 'Many afternoon cells pop up over paddy fields. Flash rates are high and CG strikes hit farmers in open fields.',
  },
  {
    id: 'mumbai-monsoon',
    name: 'Mumbai monsoon cell',
    region: 'Konkan / Mumbai',
    regime: 'monsoon_convection',
    center: [72.95, 19.1],
    zoom: 7.6,
    bbox: [71.4, 17.6, 74.6, 20.6],
    steeringDeg: 75,
    steeringKmh: 22,
    startHourIST: 16,
    month: 7,
    cape: 1800,
    shear: 9,
    pw: 66,
    cells: [
      { lng: 72.4, lat: 19.0, type: 'multicell', strength: 0.8, delayMin: 0 },
      { lng: 72.2, lat: 18.6, type: 'pulse', strength: 0.55, delayMin: 10 },
      { lng: 72.6, lat: 19.6, type: 'pulse', strength: 0.5, delayMin: 22 },
    ],
    spawnRatePerHour: 4,
    landUse: 'urban',
    description: 'Moist monsoon cells drift in from the Arabian Sea. Rain rates exceed 50 mm/h over Mumbai. Lightning is modest.',
  },
  {
    id: 'delhi-dust-thunder',
    name: 'Delhi NCR dust-thunder squall',
    region: 'Delhi NCR / Haryana',
    regime: 'nw_dust_thunder',
    center: [77.1, 28.7],
    zoom: 7.3,
    bbox: [74.8, 26.9, 79.4, 30.5],
    steeringDeg: 115,
    steeringKmh: 45,
    startHourIST: 17,
    month: 5,
    cape: 2200,
    shear: 16,
    pw: 30,
    cells: [
      { lng: 75.9, lat: 29.4, type: 'squall', strength: 0.8, delayMin: 0 },
      { lng: 76.3, lat: 29.8, type: 'multicell', strength: 0.6, delayMin: 10 },
    ],
    spawnRatePerHour: 3,
    landUse: 'urban',
    description: 'A dry squall from Rajasthan brings dust, 70-90 km/h downburst gusts and scattered lightning to Delhi NCR.',
  },
  {
    id: 'odisha-coastal',
    name: 'Odisha coastal storm',
    region: 'Coastal Odisha',
    regime: 'premonsoon_norwester',
    center: [85.8, 20.3],
    zoom: 7.3,
    bbox: [83.8, 18.6, 88.0, 22.2],
    steeringDeg: 140,
    steeringKmh: 35,
    startHourIST: 14.5,
    month: 5,
    cape: 3100,
    shear: 15,
    pw: 52,
    cells: [
      { lng: 85.0, lat: 21.0, type: 'supercell', strength: 0.9, delayMin: 0 },
      { lng: 85.5, lat: 21.4, type: 'multicell', strength: 0.65, delayMin: 10 },
      { lng: 84.7, lat: 20.4, type: 'pulse', strength: 0.5, delayMin: 25 },
    ],
    spawnRatePerHour: 4,
    landUse: 'coastal',
    description: 'A rotating supercell moves toward Bhubaneswar and Puri. Fishing boats are exposed and hail is likely.',
  },
  {
    id: 'vidarbha-marathwada',
    name: 'Vidarbha-Marathwada afternoon cells',
    region: 'Vidarbha / Marathwada',
    regime: 'premonsoon_norwester',
    center: [77.8, 20.1],
    zoom: 7.0,
    bbox: [75.2, 18.2, 80.4, 22.0],
    steeringDeg: 60,
    steeringKmh: 25,
    startHourIST: 14,
    month: 4,
    cape: 2700,
    shear: 11,
    pw: 38,
    cells: [
      { lng: 77.2, lat: 19.6, type: 'pulse', strength: 0.7, delayMin: 0 },
      { lng: 78.3, lat: 20.5, type: 'multicell', strength: 0.8, delayMin: 6 },
      { lng: 76.5, lat: 19.2, type: 'pulse', strength: 0.55, delayMin: 18 },
      { lng: 79.1, lat: 20.9, type: 'pulse', strength: 0.5, delayMin: 30 },
    ],
    spawnRatePerHour: 7,
    landUse: 'farmland',
    description: 'Hot afternoon cells over cotton and soybean fields. Hail risk for crops and CG lightning risk for farm workers.',
  },
];

export const scenarioById = (id: string) => SCENARIOS.find((s) => s.id === id) ?? SCENARIOS[0];
